# Generated by Django 3.1.5 on 2023-05-05 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmsAreaMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bms_area_master ',
            },
        ),
        migrations.CreateModel(
            name='BmsBuildingMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bms_building_master',
            },
        ),
        migrations.CreateModel(
            name='BmsDepartmentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bms_department_master',
            },
        ),
        migrations.CreateModel(
            name='BmsDeviceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(blank=True, choices=[('LED', 'LED'), ('AC', 'AC'), ('TV', 'TV'), ('Curtain', 'curtain '), ('PRJ', 'Projector'), ('AVR', 'AVR'), ('MP', 'MP'), ('BRP', 'BRP'), ('STB', 'STB')], max_length=100)),
                ('is_used', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=23)),
                ('device_informations', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('create_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_user_details_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bms_device_information',
            },
        ),
        migrations.CreateModel(
            name='BmsHardwareTypeMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hardware_name', models.CharField(blank=True, choices=[('Relay', 'Relay'), ('Dali', 'Dali'), ('CoolMaster', 'CoolMaster')], max_length=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bms_hardware_type_master',
            },
        ),
        migrations.CreateModel(
            name='BmsUserAreaCardsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
                ('card_name', models.CharField(blank=True, max_length=100)),
                ('devices_details', models.JSONField(blank=True, default=dict, null=True)),
                ('card_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsuser')),
            ],
            options={
                'db_table': 'bms_user_area_cards List',
            },
        ),
        migrations.CreateModel(
            name='BmsSubAreaMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_area_name', models.CharField(max_length=100)),
                ('on_image_path', models.CharField(blank=True, max_length=255)),
                ('off_image_path', models.CharField(blank=True, max_length=255)),
                ('width', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=100)),
                ('seating_capacity', models.BigIntegerField()),
                ('devices_details', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('area_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas_data', to='Device.bmsareamaster')),
            ],
            options={
                'db_table': 'bms_sub_area_master',
            },
        ),
        migrations.CreateModel(
            name='BmsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_data', models.JSONField(default=dict, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsmodulemaster')),
            ],
            options={
                'db_table': 'bms_settings',
            },
        ),
        migrations.CreateModel(
            name='BmsLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Big', 'Big')], default='Normal', max_length=100)),
                ('locker_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_area_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmssubareamaster')),
            ],
            options={
                'db_table': 'bms_locker',
            },
        ),
        migrations.CreateModel(
            name='BmsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Newuser', 'Newuser'), ('Visitor', 'Visitor'), ('Access', 'Access'), ('Conference', 'Conference')], max_length=100)),
                ('description', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsuser')),
            ],
            options={
                'db_table': 'bms_history',
            },
        ),
        migrations.CreateModel(
            name='BmsFloorMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('tower_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floor_data', to='Device.bmsbuildingmaster')),
            ],
            options={
                'db_table': 'bms_floor_master',
            },
        ),
        migrations.CreateModel(
            name='BmsDeviceTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type_slug', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hardware_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmshardwaretypemaster')),
            ],
            options={
                'db_table': 'bms_device_type_master',
            },
        ),
        migrations.CreateModel(
            name='BmsDeviceStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_status', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('device_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmssubareamaster')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsuser')),
            ],
            options={
                'db_table': 'bms_device_status_history',
            },
        ),
        migrations.AddField(
            model_name='bmsareamaster',
            name='floor_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_data', to='Device.bmsfloormaster'),
        ),
        migrations.CreateModel(
            name='BmsAccessControlRfidMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_no', models.IntegerField()),
                ('card_type', models.CharField(choices=[('No-assign', 'No-assign'), ('Static', 'Static'), ('Dynamic', 'Dynamic')], max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='Active', max_length=100)),
                ('access_start_time', models.DateField(default=django.utils.timezone.now)),
                ('access_end_time', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('access_area_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.bmssubareamaster')),
                ('user_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authenticate.bmsuser')),
            ],
            options={
                'db_table': 'bms_access_control_rfid_master',
            },
        ),
    ]
